[2023-06-16T20:28:23.474+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_dag.executor_task scheduled__2023-06-16T18:00:00+00:00 [queued]>
[2023-06-16T20:28:23.682+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_dag.executor_task scheduled__2023-06-16T18:00:00+00:00 [queued]>
[2023-06-16T20:28:23.683+0000] {taskinstance.py:1308} INFO - Starting attempt 4 of 4
[2023-06-16T20:28:23.923+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): executor_task> on 2023-06-16 18:00:00+00:00
[2023-06-16T20:28:23.931+0000] {standard_task_runner.py:57} INFO - Started process 599 to run task
[2023-06-16T20:28:24.310+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'demo_dag', 'executor_task', 'scheduled__2023-06-16T18:00:00+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/demo_dag.py', '--cfg-path', '/tmp/tmpnka12736']
[2023-06-16T20:28:24.313+0000] {standard_task_runner.py:85} INFO - Job 82: Subtask executor_task
[2023-06-16T20:28:26.043+0000] {task_command.py:410} INFO - Running <TaskInstance: demo_dag.executor_task scheduled__2023-06-16T18:00:00+00:00 [running]> on host 92863fbca0bd
[2023-06-16T20:28:27.443+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:205: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-06-16T20:28:28.885+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='personaltraingcp@gmail.com' AIRFLOW_CTX_DAG_OWNER='Leyner_Bejarano' AIRFLOW_CTX_DAG_ID='demo_dag' AIRFLOW_CTX_TASK_ID='executor_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-16T18:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-16T18:00:00+00:00'
[2023-06-16T20:28:30.030+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-16T20:28:30.031+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', ' \n        cd /opt/***/dags/scripts &&\n        pip install -r requirements.txt &&\n        python lambdaExecutor.py -dt 2023-06-16 -dh 18 -q https://sqs.us-east-2.amazonaws.com/147929168898/lokaInterviewSQS -ak AKIASE4KD7QBGVHE4G7U -sk AKIASE4KD7QBGVHE4G7U &&\n        pip freeze\n        ']
[2023-06-16T20:28:30.371+0000] {subprocess.py:86} INFO - Output:
[2023-06-16T20:29:00.131+0000] {subprocess.py:93} INFO - Defaulting to user installation because normal site-packages is not writeable
[2023-06-16T20:29:04.365+0000] {subprocess.py:93} INFO - Collecting boto3==1.26.151 (from -r requirements.txt (line 1))
[2023-06-16T20:29:04.490+0000] {subprocess.py:93} INFO -   Downloading boto3-1.26.151-py3-none-any.whl (135 kB)
[2023-06-16T20:29:04.707+0000] {subprocess.py:93} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.6/135.6 kB 594.3 kB/s eta 0:00:00
[2023-06-16T20:29:06.783+0000] {subprocess.py:93} INFO - Collecting botocore==1.29.151 (from -r requirements.txt (line 2))
[2023-06-16T20:29:06.819+0000] {subprocess.py:93} INFO -   Downloading botocore-1.29.151-py3-none-any.whl (10.9 MB)
[2023-06-16T20:29:13.894+0000] {subprocess.py:93} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 1.5 MB/s eta 0:00:00
[2023-06-16T20:29:15.059+0000] {subprocess.py:93} INFO - Collecting fastavro==1.7.4 (from -r requirements.txt (line 3))
[2023-06-16T20:29:15.094+0000] {subprocess.py:93} INFO -   Downloading fastavro-1.7.4-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.4 MB)
[2023-06-16T20:29:16.036+0000] {subprocess.py:93} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 2.6 MB/s eta 0:00:00
[2023-06-16T20:29:16.058+0000] {subprocess.py:93} INFO - Requirement already satisfied: pandas in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (1.3.5)
[2023-06-16T20:29:16.061+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-dateutil==2.8.2 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (2.8.2)
[2023-06-16T20:29:16.064+0000] {subprocess.py:93} INFO - Requirement already satisfied: pytz==2023.3 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 6)) (2023.3)
[2023-06-16T20:29:16.066+0000] {subprocess.py:93} INFO - Requirement already satisfied: s3transfer==0.6.1 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 7)) (0.6.1)
[2023-06-16T20:29:16.069+0000] {subprocess.py:93} INFO - Requirement already satisfied: six==1.16.0 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 8)) (1.16.0)
[2023-06-16T20:29:16.625+0000] {subprocess.py:93} INFO - Collecting tzdata==2023.3 (from -r requirements.txt (line 9))
[2023-06-16T20:29:16.656+0000] {subprocess.py:93} INFO -   Downloading tzdata-2023.3-py2.py3-none-any.whl (341 kB)
[2023-06-16T20:29:17.042+0000] {subprocess.py:93} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 341.8/341.8 kB 874.3 kB/s eta 0:00:00
[2023-06-16T20:29:17.517+0000] {subprocess.py:93} INFO - Collecting urllib3==1.26.16 (from -r requirements.txt (line 10))
[2023-06-16T20:29:17.549+0000] {subprocess.py:93} INFO -   Downloading urllib3-1.26.16-py2.py3-none-any.whl (143 kB)
[2023-06-16T20:29:17.734+0000] {subprocess.py:93} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.1/143.1 kB 753.5 kB/s eta 0:00:00
[2023-06-16T20:29:18.243+0000] {subprocess.py:93} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.7/site-packages (from boto3==1.26.151->-r requirements.txt (line 1)) (0.10.0)
[2023-06-16T20:29:20.100+0000] {subprocess.py:93} INFO - Requirement already satisfied: numpy>=1.17.3 in /home/***/.local/lib/python3.7/site-packages (from pandas->-r requirements.txt (line 4)) (1.21.6)
[2023-06-16T20:29:52.435+0000] {subprocess.py:93} INFO - Installing collected packages: urllib3, tzdata, fastavro, botocore, boto3
[2023-06-16T20:29:52.435+0000] {subprocess.py:93} INFO -   Attempting uninstall: urllib3
[2023-06-16T20:29:52.439+0000] {subprocess.py:93} INFO -     Found existing installation: urllib3 1.26.15
[2023-06-16T20:29:52.472+0000] {subprocess.py:93} INFO -     Uninstalling urllib3-1.26.15:
[2023-06-16T20:29:53.495+0000] {subprocess.py:93} INFO -       Successfully uninstalled urllib3-1.26.15
[2023-06-16T20:29:55.212+0000] {subprocess.py:93} INFO -   Attempting uninstall: botocore
[2023-06-16T20:29:55.214+0000] {subprocess.py:93} INFO -     Found existing installation: botocore 1.29.76
[2023-06-16T20:29:57.145+0000] {subprocess.py:93} INFO -     Uninstalling botocore-1.29.76:
[2023-06-16T20:30:12.230+0000] {subprocess.py:93} INFO -       Successfully uninstalled botocore-1.29.76
[2023-06-16T20:30:20.968+0000] {subprocess.py:93} INFO -   Attempting uninstall: boto3
[2023-06-16T20:30:20.970+0000] {subprocess.py:93} INFO -     Found existing installation: boto3 1.26.76
[2023-06-16T20:30:22.073+0000] {subprocess.py:93} INFO -     Uninstalling boto3-1.26.76:
[2023-06-16T20:30:36.049+0000] {subprocess.py:93} INFO -       Successfully uninstalled boto3-1.26.76
[2023-06-16T20:30:44.870+0000] {subprocess.py:93} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2023-06-16T20:30:44.968+0000] {subprocess.py:93} INFO - aiobotocore 2.5.0 requires botocore<1.29.77,>=1.29.76, but you have botocore 1.29.151 which is incompatible.
[2023-06-16T20:30:44.968+0000] {subprocess.py:93} INFO - Successfully installed boto3-1.26.151 botocore-1.29.151 fastavro-1.7.4 tzdata-2023.3 urllib3-1.26.16
[2023-06-16T20:31:02.838+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-06-16T20:31:02.838+0000] {subprocess.py:93} INFO -   File "lambdaExecutor.py", line 25, in <module>
[2023-06-16T20:31:02.838+0000] {subprocess.py:93} INFO -     vArgs = ArgParser.fn_get_args()
[2023-06-16T20:31:02.839+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scripts/lambdaExecutorUT.py", line 20, in fn_get_args
[2023-06-16T20:31:02.839+0000] {subprocess.py:93} INFO -     epilog = cls.MODULE_EPILOG, version = cls.MODULE_VERSION)
[2023-06-16T20:31:02.839+0000] {subprocess.py:93} INFO - TypeError: __init__() got an unexpected keyword argument 'version'
[2023-06-16T20:31:02.871+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-16T20:31:03.023+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-16T20:31:03.150+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=demo_dag, task_id=executor_task, execution_date=20230616T180000, start_date=20230616T202823, end_date=20230616T203103
[2023-06-16T20:31:03.349+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 82 for task executor_task (Bash command failed. The command returned a non-zero exit code 1.; 599)
[2023-06-16T20:31:03.401+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-16T20:31:03.425+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
