[2023-06-16T19:10:44.963+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_dag.executor_task scheduled__2023-06-16T18:00:00+00:00 [queued]>
[2023-06-16T19:10:44.976+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_dag.executor_task scheduled__2023-06-16T18:00:00+00:00 [queued]>
[2023-06-16T19:10:44.976+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 4
[2023-06-16T19:10:45.070+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): executor_task> on 2023-06-16 18:00:00+00:00
[2023-06-16T19:10:45.080+0000] {standard_task_runner.py:57} INFO - Started process 813 to run task
[2023-06-16T19:10:45.083+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'demo_dag', 'executor_task', 'scheduled__2023-06-16T18:00:00+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/demo_dag.py', '--cfg-path', '/tmp/tmpxqp_pakk']
[2023-06-16T19:10:45.086+0000] {standard_task_runner.py:85} INFO - Job 77: Subtask executor_task
[2023-06-16T19:10:45.226+0000] {task_command.py:410} INFO - Running <TaskInstance: demo_dag.executor_task scheduled__2023-06-16T18:00:00+00:00 [running]> on host 8a083ed08814
[2023-06-16T19:10:45.386+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:205: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-06-16T19:10:45.424+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='personaltraingcp@gmail.com' AIRFLOW_CTX_DAG_OWNER='Leyner_Bejarano' AIRFLOW_CTX_DAG_ID='demo_dag' AIRFLOW_CTX_TASK_ID='executor_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-16T18:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-16T18:00:00+00:00'
[2023-06-16T19:10:45.425+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-16T19:10:45.425+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', ' \n        cd /opt/***/dags/scripts &&\n        pip install -r requirements.txt &&\n        python lambdaExecutor.py -dt 2023-06-16 -dh 18 -q https://sqs.us-east-2.amazonaws.com/147929168898/lokaInterviewSQS &&\n        pip freeze\n        ']
[2023-06-16T19:10:45.436+0000] {subprocess.py:86} INFO - Output:
[2023-06-16T19:10:46.653+0000] {subprocess.py:93} INFO - Defaulting to user installation because normal site-packages is not writeable
[2023-06-16T19:10:46.830+0000] {subprocess.py:93} INFO - Requirement already satisfied: boto3==1.26.151 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (1.26.151)
[2023-06-16T19:10:46.831+0000] {subprocess.py:93} INFO - Requirement already satisfied: botocore==1.29.151 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (1.29.151)
[2023-06-16T19:10:46.832+0000] {subprocess.py:93} INFO - Requirement already satisfied: fastavro==1.7.4 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (1.7.4)
[2023-06-16T19:10:46.832+0000] {subprocess.py:93} INFO - Requirement already satisfied: pandas in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (1.3.5)
[2023-06-16T19:10:46.833+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-dateutil==2.8.2 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (2.8.2)
[2023-06-16T19:10:46.834+0000] {subprocess.py:93} INFO - Requirement already satisfied: pytz==2023.3 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 6)) (2023.3)
[2023-06-16T19:10:46.835+0000] {subprocess.py:93} INFO - Requirement already satisfied: s3transfer==0.6.1 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 7)) (0.6.1)
[2023-06-16T19:10:46.835+0000] {subprocess.py:93} INFO - Requirement already satisfied: six==1.16.0 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 8)) (1.16.0)
[2023-06-16T19:10:46.836+0000] {subprocess.py:93} INFO - Requirement already satisfied: tzdata==2023.3 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 9)) (2023.3)
[2023-06-16T19:10:46.837+0000] {subprocess.py:93} INFO - Requirement already satisfied: urllib3==1.26.16 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 10)) (1.26.16)
[2023-06-16T19:10:46.844+0000] {subprocess.py:93} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.7/site-packages (from boto3==1.26.151->-r requirements.txt (line 1)) (0.10.0)
[2023-06-16T19:10:46.910+0000] {subprocess.py:93} INFO - Requirement already satisfied: numpy>=1.17.3 in /home/***/.local/lib/python3.7/site-packages (from pandas->-r requirements.txt (line 4)) (1.21.6)
[2023-06-16T19:10:56.259+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-06-16T19:10:56.260+0000] {subprocess.py:93} INFO -   File "lambdaExecutor.py", line 25, in <module>
[2023-06-16T19:10:56.260+0000] {subprocess.py:93} INFO -     vArgs = ArgParser.fn_get_args()
[2023-06-16T19:10:56.260+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scripts/lambdaExecutorUT.py", line 19, in fn_get_args
[2023-06-16T19:10:56.260+0000] {subprocess.py:93} INFO -     epilog = cls.MODULE_EPILOG, version = cls.MODULE_VERSION)
[2023-06-16T19:10:56.260+0000] {subprocess.py:93} INFO - TypeError: __init__() got an unexpected keyword argument 'version'
[2023-06-16T19:10:56.301+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-16T19:10:56.314+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-16T19:10:56.318+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=demo_dag, task_id=executor_task, execution_date=20230616T180000, start_date=20230616T191044, end_date=20230616T191056
[2023-06-16T19:10:56.503+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 77 for task executor_task (Bash command failed. The command returned a non-zero exit code 1.; 813)
[2023-06-16T19:10:56.549+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-16T19:10:56.589+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
