[2023-06-16T18:42:58.247+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_dag.executor_task scheduled__2023-06-16T17:00:00+00:00 [queued]>
[2023-06-16T18:42:58.314+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_dag.executor_task scheduled__2023-06-16T17:00:00+00:00 [queued]>
[2023-06-16T18:42:58.314+0000] {taskinstance.py:1308} INFO - Starting attempt 8 of 11
[2023-06-16T18:42:58.377+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): executor_task> on 2023-06-16 17:00:00+00:00
[2023-06-16T18:42:58.386+0000] {standard_task_runner.py:57} INFO - Started process 368 to run task
[2023-06-16T18:42:58.391+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'demo_dag', 'executor_task', 'scheduled__2023-06-16T17:00:00+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/demo_dag.py', '--cfg-path', '/tmp/tmpknjkd3lm']
[2023-06-16T18:42:58.394+0000] {standard_task_runner.py:85} INFO - Job 72: Subtask executor_task
[2023-06-16T18:42:58.657+0000] {task_command.py:410} INFO - Running <TaskInstance: demo_dag.executor_task scheduled__2023-06-16T17:00:00+00:00 [running]> on host 8a083ed08814
[2023-06-16T18:42:59.759+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:205: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-06-16T18:42:59.828+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='personaltraingcp@gmail.com' AIRFLOW_CTX_DAG_OWNER='Leyner_Bejarano' AIRFLOW_CTX_DAG_ID='demo_dag' AIRFLOW_CTX_TASK_ID='executor_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-16T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-16T17:00:00+00:00'
[2023-06-16T18:42:59.831+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-16T18:42:59.832+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', ' \n        cd /opt/***/dags/scripts &&\n        pip install -r requirements.txt &&\n        python lambdaExecutor.py -dt 2023-06-16 -dh 17 -q https://sqs.us-east-2.amazonaws.com/147929168898/lokaInterviewSQS &&\n        pip freeze\n        ']
[2023-06-16T18:42:59.975+0000] {subprocess.py:86} INFO - Output:
[2023-06-16T18:43:23.030+0000] {subprocess.py:93} INFO - Defaulting to user installation because normal site-packages is not writeable
[2023-06-16T18:43:32.879+0000] {subprocess.py:93} INFO - Requirement already satisfied: boto3==1.26.151 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (1.26.151)
[2023-06-16T18:43:32.881+0000] {subprocess.py:93} INFO - Requirement already satisfied: botocore==1.29.151 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (1.29.151)
[2023-06-16T18:43:32.884+0000] {subprocess.py:93} INFO - Requirement already satisfied: fastavro==1.7.4 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (1.7.4)
[2023-06-16T18:43:32.885+0000] {subprocess.py:93} INFO - Requirement already satisfied: pandas in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (1.3.5)
[2023-06-16T18:43:32.887+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-dateutil==2.8.2 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (2.8.2)
[2023-06-16T18:43:32.890+0000] {subprocess.py:93} INFO - Requirement already satisfied: pytz==2023.3 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 6)) (2023.3)
[2023-06-16T18:43:32.891+0000] {subprocess.py:93} INFO - Requirement already satisfied: s3transfer==0.6.1 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 7)) (0.6.1)
[2023-06-16T18:43:32.893+0000] {subprocess.py:93} INFO - Requirement already satisfied: six==1.16.0 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 8)) (1.16.0)
[2023-06-16T18:43:32.895+0000] {subprocess.py:93} INFO - Requirement already satisfied: tzdata==2023.3 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 9)) (2023.3)
[2023-06-16T18:43:32.897+0000] {subprocess.py:93} INFO - Requirement already satisfied: urllib3==1.26.16 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 10)) (1.26.16)
[2023-06-16T18:43:32.917+0000] {subprocess.py:93} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.7/site-packages (from boto3==1.26.151->-r requirements.txt (line 1)) (0.10.0)
[2023-06-16T18:43:34.142+0000] {subprocess.py:93} INFO - Requirement already satisfied: numpy>=1.17.3 in /home/***/.local/lib/python3.7/site-packages (from pandas->-r requirements.txt (line 4)) (1.21.6)
[2023-06-16T18:43:54.260+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-06-16T18:43:54.260+0000] {subprocess.py:93} INFO -   File "lambdaExecutor.py", line 7, in <module>
[2023-06-16T18:43:54.260+0000] {subprocess.py:93} INFO -     from scripts.lambdaExecutorUT import ArgParser
[2023-06-16T18:43:54.260+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'scripts'
[2023-06-16T18:43:54.311+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-16T18:43:54.328+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-16T18:43:54.334+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=demo_dag, task_id=executor_task, execution_date=20230616T170000, start_date=20230616T184258, end_date=20230616T184354
[2023-06-16T18:43:54.369+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 72 for task executor_task (Bash command failed. The command returned a non-zero exit code 1.; 368)
[2023-06-16T18:43:54.392+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-16T18:43:54.432+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
