[2023-06-16T18:00:19.704+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_dag.executor_task scheduled__2023-06-16T17:00:00+00:00 [queued]>
[2023-06-16T18:00:19.909+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_dag.executor_task scheduled__2023-06-16T17:00:00+00:00 [queued]>
[2023-06-16T18:00:19.910+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 4
[2023-06-16T18:00:19.981+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): executor_task> on 2023-06-16 17:00:00+00:00
[2023-06-16T18:00:19.990+0000] {standard_task_runner.py:57} INFO - Started process 1068 to run task
[2023-06-16T18:00:19.997+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'demo_dag', 'executor_task', 'scheduled__2023-06-16T17:00:00+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/demo_dag.py', '--cfg-path', '/tmp/tmp162estgr']
[2023-06-16T18:00:20.000+0000] {standard_task_runner.py:85} INFO - Job 62: Subtask executor_task
[2023-06-16T18:00:20.097+0000] {task_command.py:410} INFO - Running <TaskInstance: demo_dag.executor_task scheduled__2023-06-16T17:00:00+00:00 [running]> on host c01f9dbc1aeb
[2023-06-16T18:00:20.441+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:205: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-06-16T18:00:20.552+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='personaltraingcp@gmail.com' AIRFLOW_CTX_DAG_OWNER='Leyner_Bejarano' AIRFLOW_CTX_DAG_ID='demo_dag' AIRFLOW_CTX_TASK_ID='executor_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-16T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-16T17:00:00+00:00'
[2023-06-16T18:00:20.554+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-16T18:00:20.577+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', ' \n        cd /opt/***/dags &&\n        pip install -r requirements.txt &&\n        python lambdaExecutor.py -dt 2023-06-16 -dh 17 -q https://sqs.us-east-2.amazonaws.com/147929168898/lokaInterviewSQS &&\n        pip freeze\n        ']
[2023-06-16T18:00:20.669+0000] {subprocess.py:86} INFO - Output:
[2023-06-16T18:00:29.818+0000] {subprocess.py:93} INFO - Defaulting to user installation because normal site-packages is not writeable
[2023-06-16T18:00:34.279+0000] {subprocess.py:93} INFO - Requirement already satisfied: boto3==1.26.151 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (1.26.151)
[2023-06-16T18:00:34.281+0000] {subprocess.py:93} INFO - Requirement already satisfied: botocore==1.29.151 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (1.29.151)
[2023-06-16T18:00:34.283+0000] {subprocess.py:93} INFO - Requirement already satisfied: fastavro==1.7.4 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (1.7.4)
[2023-06-16T18:00:34.283+0000] {subprocess.py:93} INFO - Requirement already satisfied: pandas in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (1.3.5)
[2023-06-16T18:00:34.285+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-dateutil==2.8.2 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (2.8.2)
[2023-06-16T18:00:34.286+0000] {subprocess.py:93} INFO - Requirement already satisfied: pytz==2023.3 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 6)) (2023.3)
[2023-06-16T18:00:34.287+0000] {subprocess.py:93} INFO - Requirement already satisfied: s3transfer==0.6.1 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 7)) (0.6.1)
[2023-06-16T18:00:34.289+0000] {subprocess.py:93} INFO - Requirement already satisfied: six==1.16.0 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 8)) (1.16.0)
[2023-06-16T18:00:34.291+0000] {subprocess.py:93} INFO - Requirement already satisfied: tzdata==2023.3 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 9)) (2023.3)
[2023-06-16T18:00:34.292+0000] {subprocess.py:93} INFO - Requirement already satisfied: urllib3==1.26.16 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 10)) (1.26.16)
[2023-06-16T18:00:34.395+0000] {subprocess.py:93} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.7/site-packages (from boto3==1.26.151->-r requirements.txt (line 1)) (0.10.0)
[2023-06-16T18:00:34.992+0000] {subprocess.py:93} INFO - Requirement already satisfied: numpy>=1.17.3 in /home/***/.local/lib/python3.7/site-packages (from pandas->-r requirements.txt (line 4)) (1.21.6)
[2023-06-16T18:01:03.056+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-06-16T18:01:03.057+0000] {subprocess.py:93} INFO -   File "lambdaExecutor.py", line 8, in <module>
[2023-06-16T18:01:03.058+0000] {subprocess.py:93} INFO -     from lambdaExecutorBL import LambdaExecutorBL
[2023-06-16T18:01:03.059+0000] {subprocess.py:93} INFO - ImportError: cannot import name 'LambdaExecutorBL' from 'lambdaExecutorBL' (/opt/***/dags/lambdaExecutorBL.py)
[2023-06-16T18:01:03.121+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-16T18:01:03.139+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-16T18:01:03.161+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=demo_dag, task_id=executor_task, execution_date=20230616T170000, start_date=20230616T180019, end_date=20230616T180103
[2023-06-16T18:01:03.218+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 62 for task executor_task (Bash command failed. The command returned a non-zero exit code 1.; 1068)
[2023-06-16T18:01:03.264+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-16T18:01:03.296+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
