[2023-06-16T22:08:54.914+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_dag.executor_task manual__2019-06-01T16:00:00+00:00 [queued]>
[2023-06-16T22:08:54.926+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_dag.executor_task manual__2019-06-01T16:00:00+00:00 [queued]>
[2023-06-16T22:08:54.927+0000] {taskinstance.py:1308} INFO - Starting attempt 22 of 25
[2023-06-16T22:08:55.037+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): executor_task> on 2019-06-01 16:00:00+00:00
[2023-06-16T22:08:55.045+0000] {standard_task_runner.py:57} INFO - Started process 69 to run task
[2023-06-16T22:08:55.050+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'demo_dag', 'executor_task', 'manual__2019-06-01T16:00:00+00:00', '--job-id', '108', '--raw', '--subdir', 'DAGS_FOLDER/demo_dag.py', '--cfg-path', '/tmp/tmpqju_7buf']
[2023-06-16T22:08:55.052+0000] {standard_task_runner.py:85} INFO - Job 108: Subtask executor_task
[2023-06-16T22:08:55.233+0000] {task_command.py:410} INFO - Running <TaskInstance: demo_dag.executor_task manual__2019-06-01T16:00:00+00:00 [running]> on host 31a6f4abb1ec
[2023-06-16T22:08:55.674+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:205: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-06-16T22:08:55.964+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='personaltraingcp@gmail.com' AIRFLOW_CTX_DAG_OWNER='Leyner_Bejarano' AIRFLOW_CTX_DAG_ID='demo_dag' AIRFLOW_CTX_TASK_ID='executor_task' AIRFLOW_CTX_EXECUTION_DATE='2019-06-01T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='22' AIRFLOW_CTX_DAG_RUN_ID='manual__2019-06-01T16:00:00+00:00'
[2023-06-16T22:08:55.967+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-16T22:08:55.968+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', ' \n        cd /opt/***/dags/scripts &&\n        pip install -r requirements.txt &&\n        python lambdaExecutor.py -dt 2019-06-01 -dh 16 -q https://sqs.us-east-2.amazonaws.com/147929168898/lokaInterviewSQS -ak AKIASE4KD7QBGVHE4G7U -sk *** &&\n        pip freeze\n        ']
[2023-06-16T22:08:55.983+0000] {subprocess.py:86} INFO - Output:
[2023-06-16T22:09:03.360+0000] {subprocess.py:93} INFO - Defaulting to user installation because normal site-packages is not writeable
[2023-06-16T22:09:05.993+0000] {subprocess.py:93} INFO - Collecting boto3==1.26.151 (from -r requirements.txt (line 1))
[2023-06-16T22:09:06.109+0000] {subprocess.py:93} INFO -   Downloading boto3-1.26.151-py3-none-any.whl (135 kB)
[2023-06-16T22:09:06.307+0000] {subprocess.py:93} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.6/135.6 kB 654.9 kB/s eta 0:00:00
[2023-06-16T22:09:08.200+0000] {subprocess.py:93} INFO - Collecting botocore<1.30.0,>=1.29.151 (from boto3==1.26.151->-r requirements.txt (line 1))
[2023-06-16T22:09:08.233+0000] {subprocess.py:93} INFO -   Downloading botocore-1.29.155-py3-none-any.whl (10.9 MB)
[2023-06-16T22:09:10.581+0000] {subprocess.py:93} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 4.6 MB/s eta 0:00:00
[2023-06-16T22:09:10.673+0000] {subprocess.py:93} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.7/site-packages (from boto3==1.26.151->-r requirements.txt (line 1)) (0.10.0)
[2023-06-16T22:09:10.675+0000] {subprocess.py:93} INFO - Requirement already satisfied: s3transfer<0.7.0,>=0.6.0 in /home/***/.local/lib/python3.7/site-packages (from boto3==1.26.151->-r requirements.txt (line 1)) (0.6.1)
[2023-06-16T22:09:10.687+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/***/.local/lib/python3.7/site-packages (from botocore<1.30.0,>=1.29.151->boto3==1.26.151->-r requirements.txt (line 1)) (2.8.2)
[2023-06-16T22:09:10.689+0000] {subprocess.py:93} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.7/site-packages (from botocore<1.30.0,>=1.29.151->boto3==1.26.151->-r requirements.txt (line 1)) (1.26.15)
[2023-06-16T22:09:11.247+0000] {subprocess.py:93} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.7/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.30.0,>=1.29.151->boto3==1.26.151->-r requirements.txt (line 1)) (1.16.0)
[2023-06-16T22:09:31.345+0000] {subprocess.py:93} INFO - Installing collected packages: botocore, boto3
[2023-06-16T22:09:31.345+0000] {subprocess.py:93} INFO -   Attempting uninstall: botocore
[2023-06-16T22:09:31.348+0000] {subprocess.py:93} INFO -     Found existing installation: botocore 1.29.76
[2023-06-16T22:09:32.222+0000] {subprocess.py:93} INFO -     Uninstalling botocore-1.29.76:
[2023-06-16T22:09:44.814+0000] {subprocess.py:93} INFO -       Successfully uninstalled botocore-1.29.76
[2023-06-16T22:09:47.287+0000] {subprocess.py:93} INFO -   Attempting uninstall: boto3
[2023-06-16T22:09:47.288+0000] {subprocess.py:93} INFO -     Found existing installation: boto3 1.26.76
[2023-06-16T22:09:48.830+0000] {subprocess.py:93} INFO -     Uninstalling boto3-1.26.76:
[2023-06-16T22:09:54.245+0000] {subprocess.py:93} INFO -       Successfully uninstalled boto3-1.26.76
[2023-06-16T22:09:54.753+0000] {subprocess.py:93} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2023-06-16T22:09:54.753+0000] {subprocess.py:93} INFO - aiobotocore 2.5.0 requires botocore<1.29.77,>=1.29.76, but you have botocore 1.29.155 which is incompatible.
[2023-06-16T22:09:54.753+0000] {subprocess.py:93} INFO - Successfully installed boto3-1.26.151 botocore-1.29.155
[2023-06-16T22:09:58.479+0000] {subprocess.py:93} INFO - > /opt/***/dags/scripts/lambdaExecutor.py(24)fn_execute()
[2023-06-16T22:09:58.479+0000] {subprocess.py:93} INFO - -> self.__vBusinessLayer.launch_functions()
[2023-06-16T22:09:58.479+0000] {subprocess.py:93} INFO - (Pdb)
[2023-06-16T22:09:58.547+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-16T22:09:58.558+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-16T22:09:58.562+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=demo_dag, task_id=executor_task, execution_date=20190601T160000, start_date=20230616T220854, end_date=20230616T220958
[2023-06-16T22:09:58.658+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 108 for task executor_task (Bash command failed. The command returned a non-zero exit code 1.; 69)
[2023-06-16T22:09:58.706+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-16T22:09:58.758+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
