[2023-06-16T21:59:04.823+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_dag.executor_task manual__2019-06-01T16:00:00+00:00 [queued]>
[2023-06-16T21:59:04.839+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_dag.executor_task manual__2019-06-01T16:00:00+00:00 [queued]>
[2023-06-16T21:59:04.839+0000] {taskinstance.py:1308} INFO - Starting attempt 21 of 23
[2023-06-16T21:59:04.875+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): executor_task> on 2019-06-01 16:00:00+00:00
[2023-06-16T21:59:04.883+0000] {standard_task_runner.py:57} INFO - Started process 67 to run task
[2023-06-16T21:59:04.887+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'demo_dag', 'executor_task', 'manual__2019-06-01T16:00:00+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/demo_dag.py', '--cfg-path', '/tmp/tmpd5dsbtd0']
[2023-06-16T21:59:04.890+0000] {standard_task_runner.py:85} INFO - Job 105: Subtask executor_task
[2023-06-16T21:59:04.960+0000] {task_command.py:410} INFO - Running <TaskInstance: demo_dag.executor_task manual__2019-06-01T16:00:00+00:00 [running]> on host 8cb5500f24c8
[2023-06-16T21:59:05.079+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:205: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-06-16T21:59:05.170+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='personaltraingcp@gmail.com' AIRFLOW_CTX_DAG_OWNER='Leyner_Bejarano' AIRFLOW_CTX_DAG_ID='demo_dag' AIRFLOW_CTX_TASK_ID='executor_task' AIRFLOW_CTX_EXECUTION_DATE='2019-06-01T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='21' AIRFLOW_CTX_DAG_RUN_ID='manual__2019-06-01T16:00:00+00:00'
[2023-06-16T21:59:05.172+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-16T21:59:05.173+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', ' \n        cd /opt/***/dags/scripts &&\n        pip install -r requirements.txt &&\n        python lambdaExecutor.py -dt 2019-06-01 -dh 16 -q https://sqs.us-east-2.amazonaws.com/147929168898/lokaInterviewSQS -ak AKIASE4KD7QBGVHE4G7U -sk *** &&\n        pip freeze\n        ']
[2023-06-16T21:59:05.188+0000] {subprocess.py:86} INFO - Output:
[2023-06-16T21:59:07.944+0000] {subprocess.py:93} INFO - Defaulting to user installation because normal site-packages is not writeable
[2023-06-16T21:59:10.250+0000] {subprocess.py:93} INFO - Collecting boto3==1.26.151 (from -r requirements.txt (line 1))
[2023-06-16T21:59:10.435+0000] {subprocess.py:93} INFO -   Downloading boto3-1.26.151-py3-none-any.whl (135 kB)
[2023-06-16T21:59:10.545+0000] {subprocess.py:93} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.6/135.6 kB 1.2 MB/s eta 0:00:00
[2023-06-16T21:59:12.090+0000] {subprocess.py:93} INFO - Collecting botocore<1.30.0,>=1.29.151 (from boto3==1.26.151->-r requirements.txt (line 1))
[2023-06-16T21:59:12.128+0000] {subprocess.py:93} INFO -   Downloading botocore-1.29.155-py3-none-any.whl (10.9 MB)
[2023-06-16T21:59:15.823+0000] {subprocess.py:93} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 2.8 MB/s eta 0:00:00
[2023-06-16T21:59:15.892+0000] {subprocess.py:93} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.7/site-packages (from boto3==1.26.151->-r requirements.txt (line 1)) (0.10.0)
[2023-06-16T21:59:15.893+0000] {subprocess.py:93} INFO - Requirement already satisfied: s3transfer<0.7.0,>=0.6.0 in /home/***/.local/lib/python3.7/site-packages (from boto3==1.26.151->-r requirements.txt (line 1)) (0.6.1)
[2023-06-16T21:59:15.900+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/***/.local/lib/python3.7/site-packages (from botocore<1.30.0,>=1.29.151->boto3==1.26.151->-r requirements.txt (line 1)) (2.8.2)
[2023-06-16T21:59:15.901+0000] {subprocess.py:93} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.7/site-packages (from botocore<1.30.0,>=1.29.151->boto3==1.26.151->-r requirements.txt (line 1)) (1.26.15)
[2023-06-16T21:59:16.728+0000] {subprocess.py:93} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.7/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.30.0,>=1.29.151->boto3==1.26.151->-r requirements.txt (line 1)) (1.16.0)
[2023-06-16T21:59:30.302+0000] {subprocess.py:93} INFO - Installing collected packages: botocore, boto3
[2023-06-16T21:59:30.303+0000] {subprocess.py:93} INFO -   Attempting uninstall: botocore
[2023-06-16T21:59:30.305+0000] {subprocess.py:93} INFO -     Found existing installation: botocore 1.29.76
[2023-06-16T21:59:30.505+0000] {subprocess.py:93} INFO -     Uninstalling botocore-1.29.76:
[2023-06-16T21:59:54.042+0000] {subprocess.py:93} INFO -       Successfully uninstalled botocore-1.29.76
[2023-06-16T21:59:55.563+0000] {subprocess.py:93} INFO -   Attempting uninstall: boto3
[2023-06-16T21:59:55.565+0000] {subprocess.py:93} INFO -     Found existing installation: boto3 1.26.76
[2023-06-16T21:59:55.606+0000] {subprocess.py:93} INFO -     Uninstalling boto3-1.26.76:
[2023-06-16T21:59:55.860+0000] {subprocess.py:93} INFO -       Successfully uninstalled boto3-1.26.76
[2023-06-16T21:59:56.039+0000] {subprocess.py:93} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2023-06-16T21:59:56.040+0000] {subprocess.py:93} INFO - aiobotocore 2.5.0 requires botocore<1.29.77,>=1.29.76, but you have botocore 1.29.155 which is incompatible.
[2023-06-16T21:59:56.040+0000] {subprocess.py:93} INFO - Successfully installed boto3-1.26.151 botocore-1.29.155
[2023-06-16T21:59:58.608+0000] {subprocess.py:93} INFO - > /opt/***/dags/scripts/lambdaExecutor.py(24)fn_execute()
[2023-06-16T21:59:58.608+0000] {subprocess.py:93} INFO - -> self.__vBusinessLayer.launch_functions()
[2023-06-16T21:59:58.608+0000] {subprocess.py:93} INFO - (Pdb)
[2023-06-16T21:59:58.674+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-16T21:59:58.686+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-16T21:59:58.690+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=demo_dag, task_id=executor_task, execution_date=20190601T160000, start_date=20230616T215904, end_date=20230616T215958
[2023-06-16T21:59:58.992+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 105 for task executor_task (Bash command failed. The command returned a non-zero exit code 1.; 67)
[2023-06-16T21:59:59.036+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-16T21:59:59.074+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
