[2023-06-16T05:10:27.897+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_dag.executor_task manual__2019-06-01T16:00:00+00:00 [queued]>
[2023-06-16T05:10:28.041+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_dag.executor_task manual__2019-06-01T16:00:00+00:00 [queued]>
[2023-06-16T05:10:28.041+0000] {taskinstance.py:1308} INFO - Starting attempt 3 of 6
[2023-06-16T05:10:28.310+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): executor_task> on 2019-06-01 16:00:00+00:00
[2023-06-16T05:10:28.328+0000] {standard_task_runner.py:57} INFO - Started process 6248 to run task
[2023-06-16T05:10:28.342+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'demo_dag', 'executor_task', 'manual__2019-06-01T16:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/demo_dag.py', '--cfg-path', '/tmp/tmpzyrj9t7q']
[2023-06-16T05:10:28.349+0000] {standard_task_runner.py:85} INFO - Job 15: Subtask executor_task
[2023-06-16T05:10:28.590+0000] {task_command.py:410} INFO - Running <TaskInstance: demo_dag.executor_task manual__2019-06-01T16:00:00+00:00 [running]> on host c01f9dbc1aeb
[2023-06-16T05:10:28.903+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:205: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-06-16T05:10:28.947+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='personaltraingcp@gmail.com' AIRFLOW_CTX_DAG_OWNER='Leyner_Bejarano' AIRFLOW_CTX_DAG_ID='demo_dag' AIRFLOW_CTX_TASK_ID='executor_task' AIRFLOW_CTX_EXECUTION_DATE='2019-06-01T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2019-06-01T16:00:00+00:00'
[2023-06-16T05:10:28.948+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-16T05:10:28.949+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', ' \n        cd /opt/***/dags &&\n        pip install -r requirements.txt &&\n        python lambdaExecutor.py -dt 2019-06-01 -dh 16 -q https://sqs.us-east-2.amazonaws.com/147929168898/lokaInterviewSQS\n        ']
[2023-06-16T05:10:29.026+0000] {subprocess.py:86} INFO - Output:
[2023-06-16T05:10:30.265+0000] {subprocess.py:93} INFO - Defaulting to user installation because normal site-packages is not writeable
[2023-06-16T05:10:32.397+0000] {subprocess.py:93} INFO - Collecting boto3==1.26.151 (from -r requirements.txt (line 1))
[2023-06-16T05:10:32.402+0000] {subprocess.py:93} INFO -   Using cached boto3-1.26.151-py3-none-any.whl (135 kB)
[2023-06-16T05:10:34.009+0000] {subprocess.py:93} INFO - Collecting botocore==1.29.151 (from -r requirements.txt (line 2))
[2023-06-16T05:10:34.053+0000] {subprocess.py:93} INFO -   Using cached botocore-1.29.151-py3-none-any.whl (10.9 MB)
[2023-06-16T05:10:34.882+0000] {subprocess.py:93} INFO - Collecting fastavro==1.7.4 (from -r requirements.txt (line 3))
[2023-06-16T05:10:34.897+0000] {subprocess.py:93} INFO -   Using cached fastavro-1.7.4-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.4 MB)
[2023-06-16T05:10:34.931+0000] {subprocess.py:93} INFO - Requirement already satisfied: pandas in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (1.3.5)
[2023-06-16T05:10:34.934+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-dateutil==2.8.2 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (2.8.2)
[2023-06-16T05:10:34.936+0000] {subprocess.py:93} INFO - Requirement already satisfied: pytz==2023.3 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 6)) (2023.3)
[2023-06-16T05:10:34.937+0000] {subprocess.py:93} INFO - Requirement already satisfied: s3transfer==0.6.1 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 7)) (0.6.1)
[2023-06-16T05:10:34.939+0000] {subprocess.py:93} INFO - Requirement already satisfied: six==1.16.0 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 8)) (1.16.0)
[2023-06-16T05:10:35.222+0000] {subprocess.py:93} INFO - Collecting tzdata==2023.3 (from -r requirements.txt (line 9))
[2023-06-16T05:10:35.382+0000] {subprocess.py:93} INFO -   Downloading tzdata-2023.3-py2.py3-none-any.whl (341 kB)
[2023-06-16T05:10:35.540+0000] {subprocess.py:93} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 341.8/341.8 kB 2.3 MB/s eta 0:00:00
[2023-06-16T05:10:35.795+0000] {subprocess.py:93} INFO - Collecting urllib3==1.26.16 (from -r requirements.txt (line 10))
[2023-06-16T05:10:35.833+0000] {subprocess.py:93} INFO -   Downloading urllib3-1.26.16-py2.py3-none-any.whl (143 kB)
[2023-06-16T05:10:36.056+0000] {subprocess.py:93} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.1/143.1 kB 659.3 kB/s eta 0:00:00
[2023-06-16T05:10:36.274+0000] {subprocess.py:93} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.7/site-packages (from boto3==1.26.151->-r requirements.txt (line 1)) (0.10.0)
[2023-06-16T05:10:37.219+0000] {subprocess.py:93} INFO - Requirement already satisfied: numpy>=1.17.3 in /home/***/.local/lib/python3.7/site-packages (from pandas->-r requirements.txt (line 4)) (1.21.6)
[2023-06-16T05:11:31.261+0000] {subprocess.py:93} INFO - Installing collected packages: urllib3, tzdata, fastavro, botocore, boto3
[2023-06-16T05:11:31.261+0000] {subprocess.py:93} INFO -   Attempting uninstall: urllib3
[2023-06-16T05:11:31.265+0000] {subprocess.py:93} INFO -     Found existing installation: urllib3 1.26.15
[2023-06-16T05:11:32.918+0000] {subprocess.py:93} INFO -     Uninstalling urllib3-1.26.15:
[2023-06-16T05:11:42.255+0000] {subprocess.py:93} INFO -       Successfully uninstalled urllib3-1.26.15
[2023-06-16T05:11:46.398+0000] {subprocess.py:93} INFO -   Attempting uninstall: botocore
[2023-06-16T05:11:46.402+0000] {subprocess.py:93} INFO -     Found existing installation: botocore 1.29.76
[2023-06-16T05:11:50.949+0000] {subprocess.py:93} INFO -     Uninstalling botocore-1.29.76:
[2023-06-16T05:12:52.963+0000] {subprocess.py:93} INFO -       Successfully uninstalled botocore-1.29.76
[2023-06-16T05:12:57.007+0000] {subprocess.py:93} INFO -   Attempting uninstall: boto3
[2023-06-16T05:12:57.084+0000] {subprocess.py:93} INFO -     Found existing installation: boto3 1.26.76
[2023-06-16T05:12:57.288+0000] {subprocess.py:93} INFO -     Uninstalling boto3-1.26.76:
[2023-06-16T05:12:57.630+0000] {subprocess.py:93} INFO -       Successfully uninstalled boto3-1.26.76
[2023-06-16T05:13:03.819+0000] {subprocess.py:93} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2023-06-16T05:13:03.819+0000] {subprocess.py:93} INFO - aiobotocore 2.5.0 requires botocore<1.29.77,>=1.29.76, but you have botocore 1.29.151 which is incompatible.
[2023-06-16T05:13:03.819+0000] {subprocess.py:93} INFO - Successfully installed boto3-1.26.151 botocore-1.29.151 fastavro-1.7.4 tzdata-2023.3 urllib3-1.26.16
[2023-06-16T05:13:19.391+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-06-16T05:13:19.392+0000] {subprocess.py:93} INFO -   File "lambdaExecutor.py", line 8, in <module>
[2023-06-16T05:13:19.392+0000] {subprocess.py:93} INFO -     from lambdaExecutorBL import LambdaExecutorBL
[2023-06-16T05:13:19.392+0000] {subprocess.py:93} INFO - ImportError: cannot import name 'LambdaExecutorBL' from 'lambdaExecutorBL' (/opt/***/dags/lambdaExecutorBL.py)
[2023-06-16T05:13:19.435+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-16T05:13:19.445+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-16T05:13:20.112+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=demo_dag, task_id=executor_task, execution_date=20190601T160000, start_date=20230616T051027, end_date=20230616T051320
[2023-06-16T05:13:20.642+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 15 for task executor_task (Bash command failed. The command returned a non-zero exit code 1.; 6248)
[2023-06-16T05:13:20.689+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-16T05:13:20.756+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
