[2023-06-16T21:43:17.686+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_dag.executor_task manual__2019-06-01T16:00:00+00:00 [queued]>
[2023-06-16T21:43:17.704+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_dag.executor_task manual__2019-06-01T16:00:00+00:00 [queued]>
[2023-06-16T21:43:17.705+0000] {taskinstance.py:1308} INFO - Starting attempt 18 of 21
[2023-06-16T21:43:17.741+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): executor_task> on 2019-06-01 16:00:00+00:00
[2023-06-16T21:43:17.751+0000] {standard_task_runner.py:57} INFO - Started process 148 to run task
[2023-06-16T21:43:17.758+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'demo_dag', 'executor_task', 'manual__2019-06-01T16:00:00+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/demo_dag.py', '--cfg-path', '/tmp/tmpcuhomfut']
[2023-06-16T21:43:17.762+0000] {standard_task_runner.py:85} INFO - Job 100: Subtask executor_task
[2023-06-16T21:43:17.882+0000] {task_command.py:410} INFO - Running <TaskInstance: demo_dag.executor_task manual__2019-06-01T16:00:00+00:00 [running]> on host 6a4a685f908e
[2023-06-16T21:43:18.050+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:205: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-06-16T21:43:18.169+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='personaltraingcp@gmail.com' AIRFLOW_CTX_DAG_OWNER='Leyner_Bejarano' AIRFLOW_CTX_DAG_ID='demo_dag' AIRFLOW_CTX_TASK_ID='executor_task' AIRFLOW_CTX_EXECUTION_DATE='2019-06-01T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='18' AIRFLOW_CTX_DAG_RUN_ID='manual__2019-06-01T16:00:00+00:00'
[2023-06-16T21:43:18.290+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-16T21:43:18.291+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', ' \n        cd /opt/***/dags/scripts &&\n        pip install -r requirements.txt &&\n        python lambdaExecutor.py -dt 2019-06-01 -dh 16 -q https://sqs.us-east-2.amazonaws.com/147929168898/lokaInterviewSQS -ak AKIASE4KD7QBGVHE4G7U -sk AKIASE4KD7QBGVHE4G7U &&\n        pip freeze\n        ']
[2023-06-16T21:43:18.329+0000] {subprocess.py:86} INFO - Output:
[2023-06-16T21:43:21.981+0000] {subprocess.py:93} INFO - Defaulting to user installation because normal site-packages is not writeable
[2023-06-16T21:43:24.827+0000] {subprocess.py:93} INFO - Collecting boto3==1.26.151 (from -r requirements.txt (line 1))
[2023-06-16T21:43:24.989+0000] {subprocess.py:93} INFO -   Downloading boto3-1.26.151-py3-none-any.whl (135 kB)
[2023-06-16T21:43:25.495+0000] {subprocess.py:93} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.6/135.6 kB 252.8 kB/s eta 0:00:00
[2023-06-16T21:43:27.711+0000] {subprocess.py:93} INFO - Collecting botocore<1.30.0,>=1.29.151 (from boto3==1.26.151->-r requirements.txt (line 1))
[2023-06-16T21:43:27.745+0000] {subprocess.py:93} INFO -   Downloading botocore-1.29.155-py3-none-any.whl (10.9 MB)
[2023-06-16T21:43:30.099+0000] {subprocess.py:93} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 4.6 MB/s eta 0:00:00
[2023-06-16T21:43:30.220+0000] {subprocess.py:93} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.7/site-packages (from boto3==1.26.151->-r requirements.txt (line 1)) (0.10.0)
[2023-06-16T21:43:30.222+0000] {subprocess.py:93} INFO - Requirement already satisfied: s3transfer<0.7.0,>=0.6.0 in /home/***/.local/lib/python3.7/site-packages (from boto3==1.26.151->-r requirements.txt (line 1)) (0.6.1)
[2023-06-16T21:43:30.235+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/***/.local/lib/python3.7/site-packages (from botocore<1.30.0,>=1.29.151->boto3==1.26.151->-r requirements.txt (line 1)) (2.8.2)
[2023-06-16T21:43:30.237+0000] {subprocess.py:93} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.7/site-packages (from botocore<1.30.0,>=1.29.151->boto3==1.26.151->-r requirements.txt (line 1)) (1.26.15)
[2023-06-16T21:43:30.658+0000] {subprocess.py:93} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.7/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.30.0,>=1.29.151->boto3==1.26.151->-r requirements.txt (line 1)) (1.16.0)
[2023-06-16T21:43:44.809+0000] {subprocess.py:93} INFO - Installing collected packages: botocore, boto3
[2023-06-16T21:43:44.809+0000] {subprocess.py:93} INFO -   Attempting uninstall: botocore
[2023-06-16T21:43:44.813+0000] {subprocess.py:93} INFO -     Found existing installation: botocore 1.29.76
[2023-06-16T21:43:45.392+0000] {subprocess.py:93} INFO -     Uninstalling botocore-1.29.76:
[2023-06-16T21:44:05.842+0000] {subprocess.py:93} INFO -       Successfully uninstalled botocore-1.29.76
[2023-06-16T21:44:08.101+0000] {subprocess.py:93} INFO -   Attempting uninstall: boto3
[2023-06-16T21:44:08.106+0000] {subprocess.py:93} INFO -     Found existing installation: boto3 1.26.76
[2023-06-16T21:44:08.166+0000] {subprocess.py:93} INFO -     Uninstalling boto3-1.26.76:
[2023-06-16T21:44:08.448+0000] {subprocess.py:93} INFO -       Successfully uninstalled boto3-1.26.76
[2023-06-16T21:44:08.960+0000] {subprocess.py:93} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2023-06-16T21:44:08.960+0000] {subprocess.py:93} INFO - aiobotocore 2.5.0 requires botocore<1.29.77,>=1.29.76, but you have botocore 1.29.155 which is incompatible.
[2023-06-16T21:44:08.960+0000] {subprocess.py:93} INFO - Successfully installed boto3-1.26.151 botocore-1.29.155
[2023-06-16T21:44:16.663+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-16T21:44:16.680+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-16T21:44:16.687+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=demo_dag, task_id=executor_task, execution_date=20190601T160000, start_date=20230616T214317, end_date=20230616T214416
[2023-06-16T21:44:17.229+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 100 for task executor_task (Bash command failed. The command returned a non-zero exit code 1.; 148)
[2023-06-16T21:44:17.267+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-16T21:44:17.317+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
